sudo: false
language: node_js
node_js :
  - "10.16.2"
  - "10.16.3"
  - "12.11.1"
addons:
  apt:
    packages:
      - libssl-dev
      - liblzma-dev
cache:
  directories:
  - /tmp/software
env:
  global:
    - MONGODB_VERSION=3.6.14
    - MINICONDA_VERSION="4.6.14"
    - CONDA_GENERIC_CHANNEL="https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic/linux-64/"
    - MINICONDA_HOME="/tmp/miniconda"
    - SOFTWARE_HOME="/tmp/software"
    - FREEBAYES_VERSION="1.2.0"
    - BIOBAMBAM_VERSION="2.0.79"
    - SAMTOOLS1_VERSION="1.10.0+8_g80395dc"
before_install:
  - ./.travis/install.sh
  - export PATH="/tmp/usr/bin:${PATH}"
  - npm install -g grunt-cli
  - npm --version
  - mongo --version
  - conda --version
  - freebayes --version
  - bamstreamingmarkduplicates --version
  - samtools --version
script:
  - grunt -v
