sudo: false
language: node_js
node_js :
  - "8.15.0"
  - "6.11.4"
  - "6"
addons:
  apt:
    packages:
      - libssl-dev
      - liblzma-dev
cache:
  directories:
  - /tmp/htslib
  - /tmp/samtools
  - /tmp/freebayes
env:
  global:
    - MONGODB_VERSION=3.4.3
    - FREEBAYES_VERSION="v1.1.0"
    - BIOBAMBAM_VERSION="2.0.72-release-20170316102450"
    - HTSLIB_VERSION="1.5"
    - SAMTOOLS1_VERSION="1.5"
before_install:
  - ./.travis/install.sh
  - export PATH="/tmp/usr/bin:${PATH}"
  - npm install -g npm@4.5.0
  - npm install -g grunt-cli
  - npm --version
  - mongo --version
  - freebayes --version
  - bamstreamingmarkduplicates --version
  - samtools --version
script:
  - grunt -v
